# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD

on:
    push:
        branches: [dev]
    pull_request:
        branches: [dev]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm install

            - name: Run the tests
              run: npm test --coverage

            - name: Build
              run: npm run build
              
            - name: Code Climate Coverage Action
              uses: paambaati/codeclimate-action@v2.7.5
              
              env:
                  CC_TEST_REPORTER_ID: bb05a3c12d69d8522ff8d01cc40e93e6a4014e7d98ff609c042094f3903d5060
              with:
                  coverageCommand: npm run coverage
            
